<?php

use Drupal\Core\Url;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_language_switch_links_alter().
 */
function tm_landing_page_language_switch_links_alter(array &$links, $type, Url $url) {
  $currentLangcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $logged_in = \Drupal::currentUser()->isAuthenticated();

  $params = \Drupal::routeMatch()->getParameters()->all();
  $entity = reset($params);

  // Overwrite only if a content entity and only if provided entity ids present

 if ($entity instanceof ContentEntityInterface) {

    if ($entity->id() == 24 || $entity->id() == 25) {
 
      // Please add your languages here
      // $links['en'], $links['de'], etc.
      // and enter the number of the node for the language
 
      $links['en']['url'] = Url::fromRoute('entity.node.canonical', ['node' => 24]);
      $links['es']['url'] = Url::fromRoute('entity.node.canonical', ['node' => 25]);

    }

  }

  foreach ($links as $langcode => &$link) {
    $link['attributes']['title'] = $link['title'];
    $link['title'] .= " (${langcode})";
    $link['attributes']['class'][] = $langcode === $currentLangcode ? 'active' : NULL;
  }


}


/**
* Implements hook_preprocess_menu() for menu.html.twig.
*
* Using this hook sets the in_active_trail on our
* redirected front page. Please make sure you set the proper
* paths here.
*/
function tm_landing_page_preprocess_menu(&$variables, $hook) {
  // We only need our main navigation
  if ($hook == 'menu__main') {
    // Get the current path and act only if on our fake frontpages
    $current_path = \Drupal::request()->getRequestUri();
    
    if ($current_path == '/node/24' || $current_path == '/node/25') {
      $items = $variables['items'];
      foreach ($items as $key => $item) {
        if ($item['url']->getRouteName() === '<front>') {
	        $variables['items'][$key]['in_active_trail'] = TRUE;
        }	
      } 
    }  
  }
}



